service: rails-new-io
image: canny-code/rails-new-io

deploy_timeout: 1200

volumes:
  - "/storage:/rails/storage"
  - "/home/deploy/rails-new-io/workspaces:/var/lib/rails-new-io/workspaces"

ssh:
  user: deploy

servers:
  web:
    hosts:
      - 5.161.247.143
    options:
      network: "private"
  job:
    hosts:
      - 5.161.247.143
    cmd: bundle exec rails solid_queue:start
    options:
      network: "private"

registry:
  server: ghcr.io
  username: trinitytakei
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64
    - arm64
  cache:
    type: registry
    image: trinitytakei/rails-new-io-build-cache
    options:  mode=max,oci-mediatypes=true

env:
  clear:
    SKIP_COVERAGE: "1"
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_LEVEL: debug
    SOLID_QUEUE_IN_PUMA: true
    FORCE_ISOLATED_RUBY_REINSTALL: true
  secret:
    - RAILS_MASTER_KEY

proxy:
  ssl: true
  host: alpha.railsnew.io

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets
