service: rails-new-io
image: canny-code/rails-new-io

volumes:
  - "/storage:/rails/storage"

ssh:
  user: deploy

servers:
  web:
    hosts:
      - 5.161.247.143
    labels:
      traefik.http.routers.rails_new_io.rule: Host(`alpha.railsnew.io`)
      traefik.http.routers.rails_new_io_secure.entrypoints: websecure
      traefik.http.routers.rails_new_io_secure.rule: Host(`alpha.railsnew.io`)
      traefik.http.routers.rails_new_io_secure.tls: true
      traefik.http.routers.rails_new_io_secure.tls.certresolver: letsencrypt
    options:
      network: "private"
  job:
    hosts:
      - 5.161.247.143
    cmd: bundle exec rails solid_queue:start
    options:
      network: "private"

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
    network: "private"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "trinity@railsnew.io"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

registry:
  server: ghcr.io
  username: trinitytakei
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  multiarch: <%= ENV["CI"].present? ? false : true %>
  cache:
    type: registry
    image: trinitytakei/rails-new-io-build-cache
    options:  mode=max,oci-mediatypes=true

env:
  clear:
    HOST: alpha.railsnew.io
    PORT: 3001
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
    SKIP_COVERAGE: "1"
  secret:
    - RAILS_MASTER_KEY
